# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iitppaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=False, max_length=250)),
                ('semester', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=500)),
                ('concatenate', models.CharField(max_length=100)),
                ('upload_paper', models.FileField(default=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Iitpsoln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=250)),
                ('upload_solutions', models.FileField(upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iitp.Iitppaper')),
            ],
        ),
    ]
