# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_image', models.FileField(blank=True, default=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_image', models.FileField(blank=True, default=False, upload_to='')),
                ('question_image', models.FileField(blank=True, default=False, upload_to='')),
                ('branch', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
                ('college', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.College')),
                ('semester', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='college_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.College'),
        ),
    ]
