# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_image', models.FileField(blank=True, default=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1_a', models.ImageField(blank=True, upload_to='')),
                ('question_1_b', models.ImageField(blank=True, upload_to='')),
                ('question_two_a', models.ImageField(blank=True, upload_to='')),
                ('question_two_b', models.ImageField(blank=True, upload_to='')),
                ('question_3_a', models.ImageField(blank=True, upload_to='')),
                ('question_3_b', models.ImageField(blank=True, upload_to='')),
                ('branch', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
                ('college', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.College')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_image', models.FileField(blank=True, default=False, upload_to='')),
                ('question_image1', models.FileField(blank=True, default=False, upload_to='')),
                ('question_image2', models.FileField(blank=True, default=False, upload_to='')),
                ('branch', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
                ('college', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.College')),
                ('semester', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='semester',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Semester'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Subject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bank.Subject'),
        ),
    ]
