# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_image', models.FileField(blank=True, default=False, upload_to='')),
                ('question_image1', models.FileField(blank=True, default=False, upload_to='')),
                ('question_image2', models.FileField(blank=True, default=False, upload_to='')),
                ('branch', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
                ('college', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.College')),
                ('semester', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Semester')),
            ],
        ),
    ]
