# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20170530_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='a',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
