# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_branch_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='question_image',
            new_name='question_image1',
        ),
        migrations.AddField(
            model_name='subject',
            name='question_image2',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
    ]
