# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reject',
            name='question_image1',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='question_image2',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='subject_image',
        ),
        migrations.AddField(
            model_name='reject',
            name='paper',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
