# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='subject',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Subject'),
        ),
    ]
