# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20170718_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reject',
            name='paper',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
    ]
