# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20170602_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='conctenate',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='upload_paper',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='album',
            name='a',
        ),
    ]
