# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_comments_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
