# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20170610_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='conctenate',
            new_name='concatenate',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='year',
            new_name='semester',
        ),
        migrations.AddField(
            model_name='album',
            name='a',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
