# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20170718_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reject',
            name='paper',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
