# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20170610_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='subject',
            field=models.CharField(default=False, max_length=250),
        ),
    ]
