# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20170718_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='branch',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch'),
        ),
        migrations.AddField(
            model_name='song',
            name='college',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.College'),
        ),
        migrations.AddField(
            model_name='song',
            name='semester',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Semester'),
        ),
    ]
