# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_album_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_type',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_logo',
            new_name='upload_solutions',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='year',
        ),
    ]
