# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20170616_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=False, max_length=250)),
                ('semester', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=500)),
                ('concatenate', models.CharField(max_length=100)),
                ('upload_paper', models.FileField(default=False, upload_to='')),
                ('a', models.FileField(default=False, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='subject',
        ),
    ]
