# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20170718_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_logo',
            new_name='upload',
        ),
    ]
