# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_branch_semester_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_image', models.FileField(default=False, upload_to=b'')),
                ('question_image', models.FileField(default=False, upload_to=b'')),
            ],
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
