# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_remove_song_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_title',
        ),
    ]
