# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20170624_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch'),
        ),
    ]
