# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20170718_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Paper',
        ),
    ]
