# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_subject_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Semester'),
        ),
    ]
