# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_subject_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='question_image',
            new_name='question_image_1',
        ),
        migrations.AddField(
            model_name='subject',
            name='question_image_2',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='question_image_3',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='question_image_4',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='question_image_5',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
