# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_auto_20170701_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='question_image_1',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subject',
            name='question_image_2',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subject',
            name='question_image_3',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subject',
            name='question_image_4',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subject',
            name='question_image_5',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
    ]
