# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_auto_20170701_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image_1', models.ImageField(blank=True, default=False, upload_to='')),
                ('question_image_2', models.ImageField(blank=True, default=False, upload_to='')),
                ('question_image_3', models.ImageField(blank=True, default=False, upload_to='')),
                ('question_image_4', models.ImageField(blank=True, default=False, upload_to='')),
                ('question_image_5', models.ImageField(blank=True, default=False, upload_to='')),
                ('branch', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
                ('college', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.College')),
                ('semester', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Semester')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='question_image_1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='question_image_2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='question_image_3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='question_image_4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='question_image_5',
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Subject'),
        ),
    ]
