# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_auto_20170703_0503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Quest',
        ),
    ]
