# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_auto_20170703_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='college',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='question_image',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
