# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_auto_20170703_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.FileField(blank=True, default=False, upload_to='')),
                ('question2', models.FileField(blank=True, default=False, upload_to='')),
                ('branch', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Branch')),
                ('college', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.College')),
                ('semester', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Semester')),
                ('subject', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Subject')),
            ],
        ),
    ]
