# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question2',
        ),
        migrations.AddField(
            model_name='question',
            name='question_1_a',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_1_b',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_3_a',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_3_b',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='questionb_2_a',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='questionb_2_b',
            field=models.ImageField(blank=True, default=False, upload_to=''),
        ),
    ]
