# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_auto_20170703_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_1_a',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_1_b',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_3_a',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_3_b',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionb_2_a',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionb_2_b',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
