# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0030_auto_20170703_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionb_2_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionb_2_b',
        ),
        migrations.AddField(
            model_name='question',
            name='questionb_two_a',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='questionb_two_b',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
