# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0031_auto_20170703_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionb_two_a',
            new_name='question_two_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionb_two_b',
            new_name='question_two_b',
        ),
    ]
